# Numpy Introduction

NumPy (Numerical Python) is a powerful library for numerical computing in Python. It provides support for multi-dimensional arrays, matrix operations, mathematical functions, and vectorized computations, making it essential for scientific computing, data analysis, and machine learning applications.

This tutorial covers the basics of NumPy, including:

- Installing NumPy
- Creating and manipulating arrays
- Indexing and slicing
- Broadcasting
- Linear algebra operations (e.g., matrix multiplication, inversion, eigenvalues)
- Useful mathematical functions

## Insalling Numpy

Before we begin, ensure that NumPy is installed in your Python environment.

You can install it using:

```bash
pip install numpy
```

In [3]:
import numpy as np
print("NumPy Version:", np.__version__)

NumPy Version: 2.2.3


## Creating and Manipulating Arrays
The core data structure in NumPy is the `ndarray` (n-dimensional array). 
You can create NumPy arrays in different ways.

Each NumPy array has attributes such as:
- `shape`: Dimensions of the array
- `size`: Total number of elements
- `dtype`: Data type of elements

### Special Arrays
NumPy provides several methods to initialize arrays with predefined values:
- `np.zeros()`: Creates an array of zeros
- `np.ones()`: Creates an array of ones
- `np.eye()`: Identity matrix
- `np.random.rand()`: Random numbers


In [4]:
# Creating 1D, 2D, and 3D arrays
arr1 = np.array([1, 2, 3, 4, 5])  # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 3D array

print("1D Array:", arr1, sep='\n')
print("2D Array:", arr2, sep='\n')
print("3D Array:", arr3, sep='\n')

print("Shape of arr2:", arr2.shape)
print("Size of arr2:", arr2.size)
print("Data type of arr2:", arr2.dtype)

1D Array:
[1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]]
3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape of arr2: (2, 3)
Size of arr2: 6
Data type of arr2: int64


In [ ]:
# Special arrays
zeros = np.zeros((3,3))
ones = np.ones((2,4))
identity = np.eye(4)  # 4x4 Identity matrix
random_arr = np.random.rand(3,3)

print("Zeros:", zeros, sep="\n")
print("Ones:", ones, sep="\n")
print("Identity Matrix:", identity, sep="\n")
print("Random Matrix:", random_arr, sep="\n")

## Indexing and Slicing

Indexing and slicing allow you to access and modify specific elements or subsets of a NumPy array. This is crucial for efficient data manipulation in numerical computing and machine learning.

### Types of Indexing in NumPy
- Basic Indexing – Accessing individual elements
- Slicing – Extracting subarrays
- Boolean Indexing – Selecting elements based on conditions
- Fancy Indexing – Selecting multiple elements at once

In [ ]:
# Accessing elements using indices - 1D Array
print("First element:", arr1[0])
print("Last element:", arr1[-1])

# Accessing elements using indices - 2D Array
print("Element at (1,1):", arr2[1, 1])
print("Element at (2,0):", arr2[1, 0])

# Accessing elements using indices - 3D Array
print("Element at (1,1):", arr3[0, 1, 1])
print("Element at (2,0):", arr3[0, 1, 0])

# Slicing - array[start:end:step]
# 1D Array Slicing
print("Elements from index 1 to 4:", arr1[1:5])
print("Every second element:", arr1[::2])
print("Reversed array:", arr1[::-1])

# 2D Array Slicing
print("First two rows:\n", arr2[:2, :])   # First two rows
print("Last two columns:\n", arr2[:, -2:])  # Last two columns
print("Sub-matrix (middle 2x2 block):\n", arr2[1:3, 1:3])

# Selecting elements greater than 25
print("Elements greater than 2:", arr1[arr1 > 2])
print("Elements greater than 2:\n", arr2[arr2 > 2])

# Selecting elements
rows = [0, 1]
cols = [1]

print("Selected elements:", arr2[rows, cols])

## Broadcasting
Broadcasting allows NumPy to perform element-wise operations efficiently without explicit loops.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10
result = arr + scalar  # Broadcasting adds 10 to all elements

print("Original Array:", arr, sep="\n")
print("After Broadcasting:", result, sep="\n")

## Matrix Operations

NumPy includes functions for matrix operations, such as:
- Dot product
- Transpose
- Inverse
- Eigenvalues

In [ ]:
A = np.array([[2, 3], [4, 5]])
B = np.array([[1, 2], [3, 4]])

# Matrix multiplication
C = np.dot(A, B)

# Transpose
A_T = A.T

# Inverse
A_inv = np.linalg.inv(A)

# Eigenvalues
eig_vals, eig_vecs = np.linalg.eig(A)

print("Matrix Multiplication:", C, sep="\n")
print("Transpose of A:", A_T, sep="\n")
print("Inverse of A:", A_inv, sep="\n")
print("Eigenvalues:", eig_vals, sep="\n")

## Element-wise mathematical operations

NumPy supports vectorized mathematical operations like:
- Exponentiation
- Square root
- Logarithm
- Trigonometry


In [ ]:
arr = np.array([1, 4, 9, 16])

sqrt_arr = np.sqrt(arr)  # Square root
exp_arr = np.exp(arr)  # Exponentiation
log_arr = np.log(arr)  # Natural log

print("Square Root:\n", sqrt_arr)
print("\nExponentiation:\n", exp_arr)
print("\nLogarithm:\n", log_arr)

# Convert angles from degrees to radians
degrees = np.array([0, 90, 180])
radians = np.deg2rad(degrees)

# Calculate sine values
sine_values = np.sin(radians)
cosine_values = np.cos(radians)

print("Sine values:", sine_values)
print("Cosine values:", cosine_values)


## Reshaping and Flatenning
- `reshape()`: Changes the shape of an array without changing data.
- `ravel()` or `flatten()`: Converts an array to 1D.


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

reshaped = arr.reshape((3,2))
flattened = arr.ravel()

print("Reshaped Array:\n", reshaped)
print("\nFlattened Array:\n", flattened)

# Visualizing Liear algebra operations with Matplotlib
Linear algebra is fundamental in various fields, including computer vision, graphics, machine learning, and physics. Understanding operations like vector transformations, matrix multiplications, and eigenvectors is crucial for applications like pose estimation, image processing, and robotics.

Matplotlib, along with NumPy, allows us to visualize these operations graphically, making abstract mathematical concepts more intuitive.

This part of the tutorial covers:
- Vectors in 2D space
- Matrix transformations (scaling, rotation, and shear)
- Eigenvectors and eigenvalues

## Summary of Linear Algebra Visualizations in Matplotlib

| **Operation**        | **Code Example**                   | **Visualization**              |
|----------------------|----------------------------------|--------------------------------|
| **Vector Plot**      | `plt.quiver(0, 0, v[0], v[1])`   | Arrows representing vectors   |
| **Vector Addition**  | `v_sum = v1 + v2`               | Triangle rule for addition    |
| **Scaling**         | `S @ v`                          | Stretching/compressing vector |
| **Rotation**        | `R @ v`                          | Rotated vectors               |
| **Eigenvectors**    | `np.linalg.eig(A)`               | Basis vectors for transformation |


In [ ]:
# Importing matplotlib
import matplotlib.pyplot as plt
# To render plots inline
%matplotlib inline

In [ ]:
# Plotting a vector
# Define vector
v = np.array([3, 4])

# Plot vector
plt.quiver(0, 0, v[0], v[1], angles='xy', scale_units='xy', scale=1, color='r')
plt.xlim(-5, 5)
plt.ylim(-5, 5)
plt.axhline(0, color='black', linewidth=0.5)
plt.axvline(0, color='black', linewidth=0.5)
plt.grid()
plt.title("2D Vector Visualization")
plt.show()

In [ ]:
# Vector addition
# Define vectors
v1 = np.array([2, 3])
v2 = np.array([3, 1])
v_sum = v1 + v2

# Plot vectors
plt.quiver(0, 0, v1[0], v1[1], angles='xy', scale_units='xy', scale=1, color='b', label='v1')
plt.quiver(v1[0], v1[1], v2[0], v2[1], angles='xy', scale_units='xy', scale=1, color='g', label='v2')
plt.quiver(0, 0, v_sum[0], v_sum[1], angles='xy', scale_units='xy', scale=1, color='r', label='v1 + v2')

plt.xlim(-1, 6)
plt.ylim(-1, 6)
plt.axhline(0, color='black', linewidth=0.5)
plt.axvline(0, color='black', linewidth=0.5)
plt.grid()
plt.legend()
plt.title("Vector Addition")
plt.show()

In [ ]:
# Scaling Transformations

# Define scaling matrix
S = np.array([[2, 0], [0, 1.5]])

# Define a vector
v = np.array([2, 3])

# Apply transformation
v_transformed = S @ v  # Matrix multiplication

# Plot original and transformed vector
plt.quiver(0, 0, v[0], v[1], angles='xy', scale_units='xy', scale=1, color='b', label="Original Vector")
plt.quiver(0, 0, v_transformed[0], v_transformed[1], angles='xy', scale_units='xy', scale=1, color='r', label="Scaled Vector")

plt.xlim(-5, 5)
plt.ylim(-5, 5)
plt.axhline(0, color='black', linewidth=0.5)
plt.axvline(0, color='black', linewidth=0.5)
plt.grid()
plt.legend()
plt.title("Scaling Transformation")
plt.show()

In [ ]:
# 2D Rotation
# Define rotation matrix (45 degrees)
theta = np.radians(45)
R = np.array([[np.cos(theta), -np.sin(theta)], 
              [np.sin(theta), np.cos(theta)]])

# Define vector
v = np.array([3, 1])

# Apply rotation
v_rotated = R @ v

# Plot original and rotated vector
plt.quiver(0, 0, v[0], v[1], angles='xy', scale_units='xy', scale=1, color='b', label="Original Vector")
plt.quiver(0, 0, v_rotated[0], v_rotated[1], angles='xy', scale_units='xy', scale=1, color='r', label="Rotated Vector")

plt.xlim(-5, 5)
plt.ylim(-5, 5)
plt.axhline(0, color='black', linewidth=0.5)
plt.axvline(0, color='black', linewidth=0.5)
plt.grid()
plt.legend()
plt.title("Rotation Transformation")
plt.show()


In [ ]:
# Eigen values and eigen vectors

# Define a transformation matrix
A = np.array([[2, 1], 
              [1, 2]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Plot eigenvectors
plt.quiver(0, 0, eigenvectors[0, 0], eigenvectors[1, 0], angles='xy', scale_units='xy', scale=1, color='r', label="Eigenvector 1")
plt.quiver(0, 0, eigenvectors[0, 1], eigenvectors[1, 1], angles='xy', scale_units='xy', scale=1, color='b', label="Eigenvector 2")

plt.xlim(-2, 2)
plt.ylim(-2, 2)
plt.axhline(0, color='black', linewidth=0.5)
plt.axvline(0, color='black', linewidth=0.5)
plt.grid()
plt.legend()
plt.title("Eigenvectors Visualization")
plt.show()


# Rotation and Translation in 3D

In 3D space, transformations like **rotation** and **translation** are fundamental in applications such as **pose estimation, robotics, and computer vision**. These transformations are typically represented using **homogeneous transformation matrices**, which allow both **rotation and translation** to be applied in a single matrix operation.  

---

## 3D Rotation
A **3D rotation matrix** rotates a point or object around an axis (**X, Y, or Z**) in 3D space.  

### Rotation Matrices for X, Y, Z Axes
The **rotation matrix** for a counterclockwise rotation by angle **θ** around:  

- **X-axis**:
  $
  R_x(\theta) =
  \begin{bmatrix}
  1 & 0 & 0 \\
  0 & \cos\theta & -\sin\theta \\
  0 & \sin\theta & \cos\theta
  \end{bmatrix}
  $
  
- **Y-axis**:
  \[
  R_y(\theta) =
  \begin{bmatrix}
  \cos\theta & 0 & \sin\theta \\
  0 & 1 & 0 \\
  -\sin\theta & 0 & \cos\theta
  \end{bmatrix}
  \]

- **Z-axis**:
  \[
  R_z(\theta) =
  \begin{bmatrix}
  \cos\theta & -\sin\theta & 0 \\
  \sin\theta & \cos\theta & 0 \\
  0 & 0 & 1
  \end{bmatrix}
  \]

---

## 3D Translation
A **translation** moves a point **(x, y, z)** by **(tx, ty, tz)**.  

\[
T =
\begin{bmatrix}
1 & 0 & 0 & t_x \\
0 & 1 & 0 & t_y \\
0 & 0 & 1 & t_z \\
0 & 0 & 0 & 1
\end{bmatrix}
\]

This translation matrix is used in **homogeneous coordinates**, where **points are represented as (x, y, z, 1)**.

---

## Combining Rotation and Translation
In **homogeneous coordinates**, a **rotation + translation** transformation is represented as:

\[
T R =
\begin{bmatrix}
R_{3×3} & t_{3×1} \\
0 & 1
\end{bmatrix}
\]

where **\( R_{3×3} \)** is the rotation matrix, and **\( t_{3×1} \)** is the translation vector.

---


In [ ]:
from mpl_toolkits.mplot3d import Axes3D

# Define a 3D rotation matrix (rotate around Z-axis by 45 degrees)
theta = np.radians(45)
R_z = np.array([
    [np.cos(theta), -np.sin(theta), 0],
    [np.sin(theta),  np.cos(theta), 0],
    [0, 0, 1]
])

# Define translation vector
t = np.array([[3], [4], [5]])

# Define a set of 3D points
points = np.array([
    [1, 2, 3],
    [2, 1, 4],
    [3, 3, 3]
]).T  # Transpose to match column vector format

# Apply rotation
rotated_points = R_z @ points

# Apply translation
translated_points = rotated_points + t

# Create 3D plot
fig = plt.figure()
ax = Axes3D(fig)
ax = fig.add_subplot(111, projection='3d')

# Plot original points as vectors (Blue)
ax.quiver(0, 0, 0, points[0], points[1], points[2], color='b', label="Original Points")

# Plot rotated points as vectors (Red)
ax.quiver(0, 0, 0, rotated_points[0], rotated_points[1], rotated_points[2], color='r', label="Rotated Points")

# Plot translated points as vectors (Green)
ax.quiver(0, 0, 0, translated_points[0], translated_points[1], translated_points[2], color='g', label="Translated Points")

# Set axis limits
ax.set_xlim([-5, 10])
ax.set_ylim([-5, 10])
ax.set_zlim([-5, 10])

# Labels and legend
ax.set_xlabel('X-axis')
ax.set_ylabel('Y-axis')
ax.set_zlabel('Z-axis')
ax.legend()
plt.title("Interactive 3D Rotation & Translation Visualization")

plt.show()
